---
# Source: lotus/charts/grafana/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: lotus-grafana
  labels:
    app: grafana
    chart: grafana-1.19.0
    heritage: Tiller
    release: lotus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lotus-grafana
subjects:
- kind: ServiceAccount
  name: lotus-grafana