---
# Source: lotus/charts/grafana/templates/role.yaml

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: lotus-grafana
  labels:
    app: grafana
    chart: grafana-1.19.0
    heritage: Tiller
    release: lotus
rules:
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [lotus-grafana]
