---
# Source: lotus/charts/grafana/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: lotus-grafana
  labels:
    app: grafana
    chart: grafana-1.19.0
    release: lotus
    heritage: Tiller
type: Opaque
data:
  admin-user: "YWRtaW4="
  admin-password: "YWRtaW4="
  ldap-toml: ""
