---
# Source: lotus/charts/grafana/templates/clusterrolebinding.yaml

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lotus-grafana-clusterrolebinding
  labels:
    app: grafana
    chart: grafana-1.19.0
    release: lotus
    heritage: Tiller
subjects:
  - kind: ServiceAccount
    name: lotus-grafana
    namespace: default
roleRef:
  kind: ClusterRole
  name: lotus-grafana-clusterrole
  apiGroup: rbac.authorization.k8s.io
