---
# Source: lotus/templates/prometheus-rbac.yaml

kind: ServiceAccount
apiVersion: v1
metadata:
  name: lotus-prometheus
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lotus-prometheus
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - services
      - pods
    verbs:
      - get
      - list
      - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lotus-prometheus
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lotus-prometheus
subjects:
- kind: ServiceAccount
  name: lotus-prometheus
  namespace: default