required = [
  "k8s.io/code-generator/cmd/client-gen"
]

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.9.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "=v0.0.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "go.opencensus.io"
  version = "=v0.18.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "v0.9.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.4"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.4"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.4"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.11.4"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    non-go = false
    go-tests = false

  [[prune.project]]
    name = "k8s.io/gengo"
    unused-packages = false
    non-go = false
    go-tests = false

